import type { Metadata } from 'next';
import TodosList from '@/components/todos-list';

export const metadata: Metadata = {
  title: 'Todo List',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="mx-auto max-w-7xl flex">
      <div>
        <TodosList />
      </div>
      <div className="flex-1">{children}</div>
    </main>
  );
}
